import { useMemo, useState } from 'react'
import { FiBell, FiCheck, FiMenu, FiX } from 'react-icons/fi'
import { useRealtimeList } from '../../hooks/useRealtimeData'

export default function Topbar({ role, name, userId, profile, onMenuOpen }) {
  const [open,setOpen]=useState(false);const portal=role==='manager'?'Executive control room':role==='employee'?'Operations desk':'Personal banking';const date=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date());const customerId=profile?.customerId||userId;const filter=role==='customer'?'customerId':undefined;const {data:loans}=useRealtimeList('loans',filter,customerId);const {data:transactions}=useRealtimeList('transactions',filter,customerId)
  const notifications=useMemo(()=>{if(role==='customer')return [...loans.map(item=>({...item,label:`Loan request ${item.status}`,detail:`PKR ${Number(item.amount||0).toLocaleString()}`})),...transactions.map(item=>({...item,label:`${item.type} request ${item.status}`,detail:`PKR ${Number(item.amount||0).toLocaleString()}`}))].sort((a,b)=>(b.updatedAt||b.createdAt||0)-(a.updatedAt||a.createdAt||0)).slice(0,8);if(role==='manager')return loans.filter(item=>item.status==='pending'&&Number(item.amount)>1000000).map(item=>({...item,label:'High-value loan approval',detail:`${item.customer} · PKR ${Number(item.amount).toLocaleString()}`}));return [...loans.filter(item=>item.status==='pending'&&Number(item.amount)<=1000000).map(item=>({...item,label:'Loan requires review',detail:`${item.customer} · PKR ${Number(item.amount).toLocaleString()}`})),...transactions.filter(item=>item.status==='pending').map(item=>({...item,label:`${item.type} requires review`,detail:`${item.customer} · PKR ${Number(item.amount).toLocaleString()}`}))].slice(0,8)},[role,loans,transactions])
  return <header className="workspace-topbar"><button className="workspace-menu" onClick={onMenuOpen} aria-label="Open navigation"><FiMenu/></button><div className="workspace-location"><span>VELTRIX / {portal.toUpperCase()}</span><b>Workspace</b></div><div className="workspace-tools"><span className="workspace-date">{date}</span><div className="notification-center"><button className="workspace-bell" aria-label="Notifications" aria-expanded={open} onClick={()=>setOpen(!open)}><FiBell/>{notifications.length>0&&<i/>}</button>{open&&<><button className="notification-away" aria-label="Close notifications" onClick={()=>setOpen(false)}/><aside className="notification-popover"><header><div><span>ACTIVITY CENTER</span><h3>Notifications</h3></div><button onClick={()=>setOpen(false)} aria-label="Close"><FiX/></button></header><div className="notification-list">{notifications.length===0?<div className="notification-empty"><FiCheck/><strong>All caught up</strong><small>No new banking activity.</small></div>:notifications.map((item,index)=><article key={`${item.id}-${index}`}><i className={`notification-status ${item.status||'pending'}`}/><span><strong>{item.label}</strong><small>{item.detail}</small><time>{item.updatedAt||item.createdAt?new Date(item.updatedAt||item.createdAt).toLocaleDateString('en-GB'):'Now'}</time></span></article>)}</div><footer>{notifications.length} notification{notifications.length===1?'':'s'}</footer></aside></>}</div><div className="workspace-user"><span>{name.slice(0,2).toUpperCase()}</span><div><b>{name}</b><small>{role}</small></div></div></div></header>
}
