import { useState } from 'react'
import { useNavigate, useOutletContext } from 'react-router-dom'
import { FiArrowDownLeft, FiArrowRight, FiArrowUpRight, FiCheck, FiCreditCard, FiDollarSign, FiDownload, FiEye, FiEyeOff, FiFileText, FiPlus, FiSend, FiShield, FiTrendingUp, FiUsers } from 'react-icons/fi'
import Button from '../components/ui/Button'
import { useRealtimeList, useRealtimeRecord } from '../hooks/useRealtimeData'
import { availableBalance } from '../services/balance'

const money = value => new Intl.NumberFormat('en-PK').format(value)
function WorkspaceIntro({ eyebrow, title, text, children }) {
  return <header className="workspace-intro"><div><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{children}</header>
}

function CustomerDashboard({ name, account, liveTransactions, liveLoans }) {
  const [hide,setHide]=useState(false)
  const navigate=useNavigate()
  const approved=liveTransactions.filter(item=>item.status==='approved'); const incoming=approved.filter(item=>item.type==='deposit').reduce((sum,item)=>sum+Number(item.amount),0); const outgoing=approved.filter(item=>['withdrawal','donation','zakat'].includes(item.type)).reduce((sum,item)=>sum+Number(item.amount),0); const balance=availableBalance(account,liveLoans,liveTransactions)
  return <div className="workspace customer-workspace">
    <WorkspaceIntro eyebrow="PERSONAL COMMAND CENTER" title={<>Good morning, <em>{name.split(' ')[0]}.</em></>} text="Your money, movement and next steps—in one calm view."><Button variant="secondary" onClick={()=>navigate('/customer/transactions')}><FiDownload/> Statement</Button></WorkspaceIntro>
    <section className="money-stage">
      <article className="balance-console"><header><span>PRIMARY / BANKING</span><button onClick={()=>setHide(!hide)}>{hide?<FiEye/>:<FiEyeOff/>}{hide?'Reveal':'Conceal'}</button></header><div className="console-balance"><small>AVAILABLE BALANCE · PKR</small><strong>{hide?'••••••':money(balance)}</strong></div><div className="console-account"><span>VELTRIX ACCOUNT</span><b>{account?.accountNumber||'Profile unavailable'}</b><i>{account?.status?.toUpperCase()||'INACTIVE'}</i></div><footer><span><small>APPROVED IN</small><b>+ PKR {money(incoming)}</b></span><span><small>APPROVED OUT</small><b>− PKR {money(outgoing)}</b></span></footer></article>
      <aside className="money-pulse"><header><span>MONTHLY PULSE</span><b>August</b></header><div className="pulse-chart"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="pulse-total"><span><small>NET MOVEMENT</small><strong>+ PKR 53,151</strong></span><b>+18.7%</b></div><p>Your incoming money is comfortably ahead of spending this month.</p></aside>
    </section>
    <section className="command-strip"><header><span>QUICK COMMANDS</span><small>What would you like to do?</small></header><div>{[
      [FiSend,'Send money','Submit transfer request',()=>navigate('/customer/requests')], [FiDollarSign,'Request finance','Start loan application',()=>navigate('/customer/requests')], [FiCreditCard,'Control cards','Cards & limits',()=>navigate('/customer/cards')], [FiFileText,'Get statement','Open transaction history',()=>navigate('/customer/transactions')],
    ].map(([Icon,title,detail,action],index)=><button key={title} onClick={action}><span>0{index+1}</span><i><Icon/></i><b>{title}<small>{detail}</small></b><FiArrowRight/></button>)}</div></section>
    <section className="activity-layout"><article className="activity-ledger"><header><div><span>LIVE LEDGER</span><h2>Recent movement</h2></div><button>Full history <FiArrowRight/></button></header><div>{approved.length===0?<div className="approval-empty"><p>No approved transactions yet.</p></div>:approved.slice(0,4).map((item,index)=>{const isIncome=item.type==='deposit';const Icon=isIncome?FiArrowDownLeft:FiArrowUpRight;return <div className="ledger-row" key={item.id}><span>0{index+1}</span><i className={isIncome?'green':'blue'}><Icon/></i><b>{item.type}<small>{item.createdAt?new Date(item.createdAt).toLocaleString('en-GB'):'—'} · {item.status}</small></b><strong className={isIncome?'positive':''}>{isIncome?'+':'−'} PKR {money(item.amount)}</strong></div>})}</div></article><aside className="spend-composition"><span>APPROVED OUTFLOW</span><h2>PKR {money(outgoing)}</h2><p>Withdrawals and giving</p><div className="spend-bar"><i/><i/><i/><i/></div>{[['Withdrawals','Live'],['Donations','Live'],['Zakat','Live'],['Other','Live']].map(([label,value],index)=><div className="spend-line" key={label}><i className={`spend-${index+1}`}/><span>{label}</span><b>{value}</b></div>)}</aside></section>
  </div>
}

function OperationsDashboard({ role, name, stats, queue }) {
  const manager=role==='manager'
  const navigate=useNavigate()
  const metrics=manager?[[FiUsers,'Total customers',money(stats.customers),'Live accounts'],[FiDollarSign,'Total balance',`PKR ${money(stats.balance)}`,'Approved funds'],[FiTrendingUp,'Loans issued',`PKR ${money(stats.loansIssued)}`,'Approved loans'],[FiShield,'Approvals',money(stats.pending),'Live pending']]:[[FiFileText,'Pending queue',money(stats.pending),'Requires action'],[FiCheck,'Closed requests',money(stats.closed),'Approved/rejected'],[FiShield,'Escalated loans',money(stats.escalated),'Manager authority'],[FiUsers,'Total customers',money(stats.customers),'Authorized records']]
  return <div className="workspace operations-workspace"><WorkspaceIntro eyebrow={manager?'EXECUTIVE CONTROL ROOM':'OPERATIONS DESK'} title={manager?'Bank performance, distilled.':`Welcome back, ${name.split(' ')[0]}.`} text={manager?'Monitor momentum, approvals and operational health across the bank.':'Your priority queue and today’s service progress.'}><Button variant={manager?'secondary':'primary'} onClick={()=>manager?window.print():navigate('/staff/customers')}>{manager?<FiDownload/>:<FiPlus/>}{manager?'Export brief':'New customer'}</Button></WorkspaceIntro>
    <section className="operations-metrics">{metrics.map(([Icon,label,value,change],index)=><article key={label}><header><span>0{index+1}</span><i><Icon/></i></header><small>{label}</small><strong>{value}</strong><p>{change}</p></article>)}</section>
    <section className="operations-grid"><article className="operations-queue"><header><div><span>PRIORITY FLOW</span><h2>{manager?'Final approvals':'Requests needing attention'}</h2></div><button onClick={()=>navigate('/staff/requests')}>Open queue <FiArrowRight/></button></header><div>{queue.length===0?<div className="approval-empty">No pending requests assigned to you.</div>:queue.slice(0,4).map((request,index)=><div className="operation-row" key={`${request.collection}-${request.id}`}><span>0{index+1}</span><b>{request.customer||'Customer'}<small>{request.purpose||request.type||'Financial request'}</small></b><strong>PKR {money(request.amount)}</strong><i className={Number(request.amount)>1000000?'urgent':''}>{request.collection==='loans'?'Loan':'Transaction'}</i><Button variant={manager?'primary':'secondary'} onClick={()=>navigate('/staff/requests')}>Review</Button></div>)}</div></article><aside className="performance-rail"><span>{manager?'BANK HEALTH':'TODAY’S PACE'}</span><div className="health-ring"><strong>{manager?'92':'78'}</strong><small>/100</small></div><h3>{manager?'Excellent condition':'On track'}</h3>{(manager?[['Customer satisfaction','94%'],['Request resolution','89%'],['Compliance','98%']]:[['Queue cleared','76%'],['Daily target','82%'],['Quality score','96%']]).map(([label,value])=><div className="rail-progress" key={label}><span>{label}<b>{value}</b></span><i><em style={{width:value}}/></i></div>)}</aside></section>
  </div>
}

export default function Dashboard(){const {role,name,userId,profile}=useOutletContext();const customerId=profile?.customerId||userId;const filter=role==='customer'?'customerId':undefined;const {data:account}=useRealtimeRecord(role==='customer'?`customers/${customerId}`:null);const {data:allTransactions}=useRealtimeList('transactions',filter,customerId);const {data:loans}=useRealtimeList('loans',filter,customerId);const {data:customers}=useRealtimeList(role==='customer'?'transactions':'customers',filter,customerId);if(role==='customer')return <CustomerDashboard name={name} account={account} liveTransactions={allTransactions} liveLoans={loans}/>;const pending=[...loans,...allTransactions].filter(item=>item.status==='pending').length;const stats={customers:customers.length,balance:customers.reduce((sum,item)=>sum+availableBalance(item,loans,allTransactions),0),loansIssued:loans.filter(item=>item.status==='approved').reduce((sum,item)=>sum+Number(item.amount||0),0),pending,closed:[...loans,...allTransactions].filter(item=>item.status!=='pending').length,escalated:loans.filter(item=>item.status==='pending'&&Number(item.amount)>1000000).length};const queue=[...loans.map(item=>({...item,collection:'loans'})),...allTransactions.map(item=>({...item,collection:'transactions'}))].filter(item=>item.status==='pending'&&(item.collection==='transactions'||(role==='manager'?Number(item.amount)>1000000:Number(item.amount)<=1000000))).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));return <OperationsDashboard role={role} name={name} stats={stats} queue={queue}/>}
