import { useState } from 'react'
import { useOutletContext } from 'react-router-dom'
import { FiEdit2, FiPlus, FiTrash2, FiUsers, FiX } from 'react-icons/fi'
import toast from 'react-hot-toast'
import Button from '../components/ui/Button'
import PageHeader from '../components/ui/PageHeader'
import SearchField from '../components/ui/SearchField'
import StatCard from '../components/ui/StatCard'
import StatusBadge from '../components/ui/StatusBadge'
import { useRealtimeList } from '../hooks/useRealtimeData'
import { provisionEmployeeAccount } from '../services/accountProvisioning'
import { deactivateEmployee, updateEmployeeRecord } from '../services/bankRepository'

const blank={name:'',email:'',password:'',salary:'',responsibility:'Customer operations',status:'active'}
export default function Employees(){
  const {role,userId}=useOutletContext();const {data:employees,loading}=useRealtimeList('employees');const [search,setSearch]=useState('');const [form,setForm]=useState(blank);const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);const [busy,setBusy]=useState(false)
  if(role!=='manager')return <div className="access-denied"><FiUsers/><h1>Manager access required</h1><p>Employee administration is restricted to managers.</p></div>
  const show=(item=null)=>{setEditing(item?.id||null);setForm(item?{...item,password:''}:blank);setOpen(true)}
  const submit=async e=>{e.preventDefault();setBusy(true);try{if(editing)await updateEmployeeRecord(editing,form,{uid:userId,role});else await provisionEmployeeAccount(form);setOpen(false);toast.success(`Employee ${editing?'updated':'created'} successfully.`)}catch(error){toast.error(error.code==='auth/email-already-in-use'?'This email already belongs to an account.':error.message)}finally{setBusy(false)}}
  const remove=async item=>{if(!window.confirm(`Deactivate ${item.name}?`))return;try{await deactivateEmployee(item.id,{uid:userId,role});toast.success(`${item.name} has been deactivated.`)}catch(error){toast.error(error.message)}}
  const shown=employees.filter(item=>`${item.name} ${item.email}`.toLowerCase().includes(search.toLowerCase()))
  return <><PageHeader eyebrow="Staff administration" title="Employee Management" action={<Button onClick={()=>show()}><FiPlus/> Add employee</Button>}/><div className="metric-grid"><StatCard icon={FiUsers} label="Total employees" value={employees.length} helper="Active authorized staff records"/></div><section className="panel customer-table"><div className="approval-toolbar"><SearchField placeholder="Search employees..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="employee-manage-head"><span>EMPLOYEE</span><span>RESPONSIBILITY</span><span>SALARY</span><span>STATUS</span><span>ACTIONS</span></div>{loading?<div className="approval-empty">Loading employees…</div>:shown.map(emp=><div className="employee-manage-row" key={emp.id}><span className="approval-person"><i>{emp.name?.slice(0,2).toUpperCase()}</i><span><strong>{emp.name}</strong><small>{emp.email}</small></span></span><span>{emp.responsibility}</span><b>PKR {Number(emp.salary).toLocaleString()}</b><StatusBadge status={emp.status}/><div><Button variant="secondary" onClick={()=>show(emp)}><FiEdit2/></Button><Button variant="secondary" onClick={()=>remove(emp)}><FiTrash2/></Button></div></div>)}</section>{open&&<div className="review-drawer-backdrop" onMouseDown={()=>setOpen(false)}><form className="review-drawer" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><span><small>STAFF ACCOUNT</small><h2>{editing?'Edit employee':'Add employee'}</h2></span><button type="button" onClick={()=>setOpen(false)}><FiX/></button></header><div className="drawer-form"><label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Email address<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required disabled={Boolean(editing)}/></label>{!editing&&<label>Temporary password<input type="password" minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label>}<label>Monthly salary (PKR)<input type="number" min="0" value={form.salary} onChange={e=>setForm({...form,salary:e.target.value})} required/></label><label>Responsibilities<select value={form.responsibility} onChange={e=>setForm({...form,responsibility:e.target.value})}><option>Customer operations</option><option>Loans & verification</option><option>Transaction processing</option><option>Compliance review</option></select></label>{editing&&<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>}</div><footer><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':editing?'Save changes':'Create employee'}</Button></footer></form></div>}</>}
