import { useState } from 'react'
import { FiArrowRight, FiBookOpen, FiBriefcase, FiCheck, FiCreditCard, FiDollarSign, FiHeadphones, FiLock, FiMenu, FiShield, FiSmartphone, FiTrendingUp, FiUser, FiX } from 'react-icons/fi'
import toast from 'react-hot-toast'
import { useAuth } from '../context/AuthContext'
import BrandLogo from '../components/ui/BrandLogo'

const accountGroups = [
  { id: 'personal', label: 'Personal', icon: FiUser, description: 'Flexible accounts for everyday life and family needs.', accounts: [
    { id: 'personal', title: 'Everyday Account', text: 'Transfers, bills, card payments and regular personal banking.', requirements: ['Valid CNIC', 'Mobile number', 'Email address'] },
    { id: 'salary', title: 'Salary Account', text: 'Receive salary with convenient digital banking and a debit card.', requirements: ['Valid CNIC', 'Employment letter', 'Employer details'] },
    { id: 'joint', title: 'Joint Account', text: 'A shared account for family members or trusted partners.', requirements: ['CNIC of all holders', 'Operating instructions', 'Source of income'] },
  ]},
  { id: 'business', label: 'Business', icon: FiBriefcase, description: 'Transaction accounts for professionals, freelancers and businesses.', accounts: [
    { id: 'current', title: 'Current Account', text: 'Frequent transactions for professionals and established businesses.', requirements: ['Valid CNIC', 'Business/job proof', 'NTN (if applicable)'] },
    { id: 'business', title: 'Business Account', text: 'Banking tools for companies, shops, startups and partnerships.', requirements: ['Business registration', 'NTN', 'Owner/director documents'] },
    { id: 'freelancer', title: 'Freelancer Account', text: 'Receive local and international income from freelance work.', requirements: ['Valid CNIC', 'Work/platform proof', 'Source of funds'] },
  ]},
  { id: 'youth', label: 'Student & Youth', icon: FiBookOpen, description: 'Simple banking for students, young people and minors.', accounts: [
    { id: 'student', title: 'Student Account', text: 'Low-cost banking designed for enrolled students.', requirements: ['Student ID/admission letter', 'B-Form or CNIC', 'Mobile number'] },
    { id: 'minor', title: 'Minor Account', text: 'A guardian-managed account for customers under 18.', requirements: ['Child B-Form', 'Guardian CNIC', 'Proof of relationship'] },
    { id: 'youth', title: 'Youth Account', text: 'Digital-first banking for young adults starting their journey.', requirements: ['Valid CNIC', 'Mobile number', 'Email address'] },
  ]},
  { id: 'investment', label: 'Savings & Investment', icon: FiTrendingUp, description: 'Options that help protect and grow your money.', accounts: [
    { id: 'savings', title: 'Savings Account', text: 'Save regularly while keeping your funds accessible.', requirements: ['Valid CNIC', 'Proof of income', 'Source of funds'] },
    { id: 'fixed-deposit', title: 'Fixed Deposit', text: 'Place funds for a selected term for an expected return.', requirements: ['Valid CNIC', 'Source of funds', 'Opening deposit'] },
    { id: 'islamic-savings', title: 'Islamic Savings', text: 'Shariah-compliant savings based on approved principles.', requirements: ['Valid CNIC', 'Source of income', 'Opening deposit'] },
  ]},
]
const services = [
  { icon: FiSmartphone, title: 'Digital Banking', text: 'Manage balances, transfers and payments from anywhere.' }, { icon: FiCreditCard, title: 'Cards & Payments', text: 'Secure debit cards with convenient everyday payments.' }, { icon: FiDollarSign, title: 'Financing', text: 'Personal and business financing with transparent terms.' }, { icon: FiTrendingUp, title: 'Savings & Growth', text: 'Purpose-built accounts to help your money work harder.' }, { icon: FiShield, title: 'Secure Banking', text: 'Modern account protection and continuous monitoring.' }, { icon: FiHeadphones, title: 'Customer Support', text: 'Helpful support whenever you need banking assistance.' },
]
function messageFor(error) { const messages = { 'auth/wrong-portal': 'This account is not registered for the selected portal.', 'auth/employee-pending': 'Your employee request is awaiting manager approval.', 'auth/employee-rejected': 'Your employee access is inactive or unauthorized.', 'auth/customer-inactive': 'This customer account is inactive. Please contact bank staff.', 'auth/invalid-credential': 'The email address or password is incorrect.', 'auth/profile-unavailable': 'Your account profile is unavailable.', 'auth/email-already-in-use': 'An account already exists with this email.', 'auth/weak-password': 'Please choose a stronger password.', 'auth/too-many-requests': 'Too many attempts. Please try again later.' }; return messages[error.code] || error.message || 'Something went wrong. Please try again.' }

export default function Login() {
  const { login,sendPasswordReset } = useAuth(); const [dialog,setDialog]=useState(null); const [mobileMenu,setMobileMenu]=useState(false); const [loading,setLoading]=useState(false); const [activeGroup,setActiveGroup]=useState('personal'); const [loginRole,setLoginRole]=useState('customer'); const [loginForm,setLoginForm]=useState({email:'',password:''})
  const submitLogin=async(e)=>{e.preventDefault();setLoading(true);try{await login(loginForm.email,loginForm.password,loginRole);toast.success('Welcome to Veltrix Finance')}catch(error){toast.error(messageFor(error))}finally{setLoading(false)}}
  const resetPassword=async()=>{setLoading(true);try{await sendPasswordReset(loginForm.email);toast.success('Reset link sent to the registered email address.')}catch(error){toast.error(messageFor(error))}finally{setLoading(false)}}
  const openDialog=(type)=>{setDialog(type);setMobileMenu(false)}
  return <div className="landing-page">
    <header className="landing-nav"><a className="landing-brand" href="#home"><BrandLogo/><span><strong>Veltrix</strong><small>FINANCE</small></span></a><nav className={mobileMenu?'open':''}><div className="nav-links"><a href="#accounts" onClick={()=>setMobileMenu(false)}>Accounts</a><a href="#services" onClick={()=>setMobileMenu(false)}>Services</a><a href="#about" onClick={()=>setMobileMenu(false)}>Our approach</a></div><div className="nav-actions"><button className="nav-login" onClick={()=>openDialog('login')}>Assigned-user login</button></div></nav><button className="landing-menu" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="Toggle navigation">{mobileMenu?<FiX/>:<FiMenu/>}</button></header>
    <main>
      <section className="landing-hero" id="home"><div className="hero-index"><span>01</span><i/><small>DIGITAL BANKING<br/>FOR REAL LIFE</small></div><div className="hero-copy"><span className="landing-eyebrow"><FiShield/> A NEW WAY TO BANK</span><h1>Money moves.<br/><em>You move better.</em></h1><p>A calm, secure financial space for customers whose verified accounts and login credentials are issued by Veltrix bank staff.</p><div className="hero-actions"><button className="landing-primary" onClick={()=>openDialog('login')}>Access digital banking <FiArrowRight/></button><a className="landing-secondary" href="#accounts">Explore account types</a></div><div className="trust-row"><span><b>24/7</b> Digital access</span><span><b>4+</b> Account families</span><span><b>100%</b> Staff-verified access</span></div></div><div className="hero-finance-board"><div className="board-note note-one"><FiTrendingUp/><span><small>Monthly growth</small><strong>+12.4%</strong></span></div><div className="hero-card"><span>VELTRIX / 2026</span><BrandLogo className="hero-mark"/><div><small>Available balance</small><strong>PKR 248,500</strong></div><p>••••  ••••  ••••  2847</p><footer><span><small>MEMBER</small>YOUR NAME</span><span><small>STATUS</small>ACTIVE</span></footer></div><div className="board-note note-two"><FiShield/><span><small>Account security</small><strong>Protected</strong></span></div><div className="board-orbit">V</div></div></section>
      <section className="landing-section services-section" id="services"><div className="section-heading"><span>THE VELTRIX SYSTEM</span><h2>One financial space.<br/>Many possibilities.</h2><p>Every essential sits together, without the clutter.</p></div><div className="services-grid">{services.map(({icon:Icon,title,text},index)=><article key={title} className={`service-tile service-${index+1}`}><span>0{index+1}</span><i><Icon/></i><div><h3>{title}</h3><p>{text}</p></div><FiArrowRight className="service-arrow"/></article>)}</div></section>
      <section className="landing-section accounts-section" id="accounts"><div className="account-intro"><span>ACCOUNT INFORMATION</span><h2>Understand your<br/>banking options.</h2><p>Compare account families and required documents. Verified accounts are created only by authorized Veltrix employees or managers.</p></div><div className="account-explorer"><div className="account-tabs" role="tablist">{accountGroups.map(({id,label,icon:Icon},index)=><button key={id} role="tab" aria-selected={activeGroup===id} className={activeGroup===id?'active':''} onClick={()=>setActiveGroup(id)}><span>0{index+1}</span><Icon/><b>{label}</b><FiArrowRight/></button>)}</div>{accountGroups.filter(group=>group.id===activeGroup).map(group=><div className="account-group" key={group.id}><header><group.icon/><div><span>INFORMATION ONLY</span><h3>{group.label}</h3><p>{group.description}</p></div></header><div className="account-grid">{group.accounts.map(({id,title,text,requirements},index)=><article key={id} className="account-card"><span>0{index+1}</span><h3>{title}</h3><p>{text}</p><h4>Required documents</h4><ul>{requirements.map(item=><li key={item}><FiCheck/>{item}</li>)}</ul><small className="staff-issued-note"><FiShield/> Issued after bank verification</small></article>)}</div></div>)}</div></section>
      <section className="landing-section why-section" id="about"><div><span className="landing-eyebrow">WHY VELTRIX FINANCE</span><h2>A bank built around secure access</h2><p>We combine useful digital tools with verified, staff-controlled account issuance so customers can bank with clarity and confidence.</p><ul><li><FiLock/><span><strong>Security comes first</strong><small>Your account is protected with modern authentication and monitoring.</small></span></li><li><FiTrendingUp/><span><strong>Built for financial progress</strong><small>Accounts and services for students, savers, families and businesses.</small></span></li><li><FiHeadphones/><span><strong>Support that listens</strong><small>Clear guidance when you need help with your account.</small></span></li></ul></div><aside><strong>How digital access is issued</strong><ol><li><b>1</b>Visit or contact authorized bank staff</li><li><b>2</b>Provide and verify required documents</li><li><b>3</b>Staff creates your customer account</li><li><b>4</b>Use assigned credentials to log in</li></ol><button className="landing-primary" onClick={()=>openDialog('login')}>Use assigned login</button></aside></section>
      <section className="landing-cta"><div><span>ALREADY A VELTRIX CUSTOMER?</span><h2>Your secure banking space is ready.</h2><p>Use the email and password assigned to you by authorized bank staff.</p></div><button onClick={()=>openDialog('login')}>Customer login <FiArrowRight/></button></section>
    </main>
    <footer className="landing-footer"><div className="landing-brand"><BrandLogo/><span><strong>Veltrix Finance</strong><small>Finance, thoughtfully connected</small></span></div><p>Secure accounts, digital banking, cards, savings and financial support for every stage of life.</p><div><a href="#accounts">Accounts</a><a href="#services">Services</a><button onClick={()=>openDialog('login')}>Online banking</button></div><small>© 2026 Veltrix Finance. All rights reserved.</small></footer>
    {dialog==='login'&&<div className="landing-modal" onMouseDown={e=>e.target===e.currentTarget&&setDialog(null)}><div className="landing-dialog"><button className="dialog-close" onClick={()=>setDialog(null)} aria-label="Close"><FiX/></button><form onSubmit={submitLogin}><span className="auth-kicker">AUTHORIZED ACCESS</span><h2>Log in to your account</h2><p>Use credentials assigned by Veltrix bank staff.</p><div className="role-picker"><button type="button" className={loginRole==='customer'?'selected':''} onClick={()=>setLoginRole('customer')}><FiUser/><span><strong>Customer</strong><small>Personal banking</small></span></button><button type="button" className={loginRole==='employee'?'selected':''} onClick={()=>setLoginRole('employee')}><FiBriefcase/><span><strong>Staff</strong><small>Employee or manager</small></span></button></div><label>Email address<input type="email" value={loginForm.email} onChange={e=>setLoginForm({...loginForm,email:e.target.value})} required/></label><label>Password<input type="password" minLength="6" value={loginForm.password} onChange={e=>setLoginForm({...loginForm,password:e.target.value})} required/></label>{loginRole==='customer'&&<button type="button" className="forgot-password" disabled={loading} onClick={resetPassword}>Forgot password? Email me a reset link</button>}<button className="landing-primary form-submit" disabled={loading}>{loading?'Logging in...':'Log in securely'}</button><small>Accounts and credentials are issued only by authorized bank staff.</small></form></div></div>}
  </div>
}
