import { useEffect, useState } from 'react'
import { FiBell, FiKey, FiLock, FiSave, FiShield, FiUser } from 'react-icons/fi'
import toast from 'react-hot-toast'
import { useAuth } from '../context/AuthContext'
import Button from '../components/ui/Button'
import PageHeader from '../components/ui/PageHeader'
import Panel, { PanelHeader } from '../components/ui/Panel'

export default function Settings(){
  const {profile,updateDisplayName,changeCustomerPassword,sendPasswordReset}=useAuth()
  const [name,setName]=useState(profile?.name||'');const [alerts,setAlerts]=useState(true);const [saving,setSaving]=useState(false)
  const [passwords,setPasswords]=useState({current:'',next:'',confirm:''});const [passwordBusy,setPasswordBusy]=useState(false)
  useEffect(()=>setName(profile?.name||''),[profile?.name])
  const save=async e=>{e.preventDefault();setSaving(true);try{await updateDisplayName(name);toast.success('Display name updated successfully.')}catch(error){toast.error(error.message||'Display name could not be updated.')}finally{setSaving(false)}}
  const changePassword=async e=>{e.preventDefault();if(passwords.next!==passwords.confirm)return toast.error('New passwords do not match.');setPasswordBusy(true);try{await changeCustomerPassword(passwords.current,passwords.next);setPasswords({current:'',next:'',confirm:''});toast.success('Password changed successfully.')}catch(error){toast.error(error.code==='auth/invalid-credential'?'Current password is incorrect.':error.message)}finally{setPasswordBusy(false)}}
  const reset=async()=>{setPasswordBusy(true);try{await sendPasswordReset(profile?.email);toast.success('Password reset link sent to your registered email.')}catch(error){toast.error(error.message)}finally{setPasswordBusy(false)}}
  const customer=profile?.role==='customer'
  return <><PageHeader eyebrow="Personal preferences" title="Settings"/><div className="settings-layout"><Panel as="form" className="settings-panel" onSubmit={save}><PanelHeader title="Profile information" description="Manage how your identity appears across Veltrix Finance."/><div className="settings-body"><label><span><FiUser/> Display name</span><input value={name} minLength="2" onChange={e=>setName(e.target.value)} required/></label><label><span>Email address</span><input value={profile?.email||''} disabled/></label><Button disabled={saving||name.trim()===profile?.name}><FiSave/> {saving?'Saving…':'Save changes'}</Button></div></Panel><Panel className="settings-panel"><PanelHeader title="Security & notifications" description="Control account protection and important alerts."/><div className="settings-body"><label className="preference-row"><span><i><FiBell/></i><b>Financial alerts<small>Receive updates for requests and account activity.</small></b></span><input type="checkbox" checked={alerts} onChange={e=>setAlerts(e.target.checked)}/></label><div className="security-row"><i><FiShield/></i><span><strong>Role-protected access</strong><small>Your permissions are secured by your verified profile.</small></span></div><div className="security-row"><i><FiLock/></i><span><strong>Secure account authentication</strong><small>Email and password authentication is active.</small></span></div></div></Panel>{customer&&<Panel as="form" className="settings-panel password-panel" onSubmit={changePassword}><PanelHeader title="Change password" description="Verify your current password before choosing a new one."/><div className="settings-body"><label><span><FiKey/> Current password</span><input type="password" autoComplete="current-password" value={passwords.current} onChange={e=>setPasswords({...passwords,current:e.target.value})} required/></label><label><span>New password</span><input type="password" minLength="8" autoComplete="new-password" value={passwords.next} onChange={e=>setPasswords({...passwords,next:e.target.value})} required/></label><label><span>Confirm new password</span><input type="password" minLength="8" autoComplete="new-password" value={passwords.confirm} onChange={e=>setPasswords({...passwords,confirm:e.target.value})} required/></label><div className="password-actions"><Button disabled={passwordBusy}><FiLock/> {passwordBusy?'Please wait…':'Change password'}</Button><Button type="button" variant="secondary" disabled={passwordBusy} onClick={reset}>Email reset link</Button></div></div></Panel>}</div></>
}
